title: ABC Lab ELN
author: ABC Lab, University of Maryland
logo: https://upload.wikimedia.org/wikipedia/commons/8/88/University_of_Maryland_seal.svg
repository:
  url: https://github.com/gugutries/abc-eln
  path_to_book: ""
  branch: main

